services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~SvID4AIw"
      - key: DATABASE_URL
        fromDatabase:https://files.catbox.moe/ly6553.jpg
          name: my-database
          property: connectionString
